import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
  docsSidebar: [
    "intro",
    {
      type: "category",
      label: "Specs",
      items: [{ type: "autogenerated", dirName: "specs" }],
    },
  ],
};

export default sidebars;
